name: EAS iOS Submit

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["EAS iOS Build"]
    types: ["completed"]

jobs:
  ios-submit:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install EAS CLI
        run: npm i -g eas-cli@latest

      - name: Submit latest iOS build to TestFlight
        run: eas submit --platform ios --profile production --non-interactive --latest
        env:
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}


