name: EAS Submit - Android

on:
  workflow_dispatch:
    inputs:
      build_id:
        description: 'EAS Build ID to submit (optional - will use latest if not provided)'
        required: false
        type: string
      submit_profile:
        description: 'Submit profile to use'
        required: false
        default: 'production'
        type: choice
        options:
          - production
      skip_binary_upload:
        description: 'Skip binary upload (if already uploaded)'
        required: false
        default: false
        type: boolean
  push:
    branches: [ main, master ]
    paths:
      - 'src/**'
      - 'app.json'
      - 'eas.json'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/submit-android.yml'
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  submit-android:
    name: Submit Android App to Google Play
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Submit Android App to Google Play
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            if [ -n "${{ github.event.inputs.build_id }}" ]; then
              echo "Submitting specific build: ${{ github.event.inputs.build_id }}"
              eas submit --platform android --profile ${{ github.event.inputs.submit_profile }} --id ${{ github.event.inputs.build_id }} --non-interactive
            else
              echo "Submitting latest Android build"
              eas submit --platform android --profile ${{ github.event.inputs.submit_profile }} --non-interactive
            fi
          else
            echo "Submitting latest Android build for tag: ${{ github.ref_name }}"
            eas submit --platform android --profile production --non-interactive
          fi
      - name: Get submission status
        run: eas submit:list --platform android --limit 1
